[workspace]
resolver = "3"
members = ["boluo", "boluo-*"]

[workspace.package]
edition = "2024"
license = "MIT"
homepage = "https://github.com/dakai-chen/boluo"
repository = "https://github.com/dakai-chen/boluo"
rust-version = "1.85"
