[package]
name = "static-file"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boluo = { path = "../../boluo", features = ["static-file"] }
tokio = { version = "1", features = ["full"] }
